### ISSUE TITLE
Ability to compile without downloading afresh

### ISSUE THREAD

**Issue by nmoinvaz** [neurolabusc/pigz-bench-python#1]
It might be a good idea to add an argument with argparse to `./a_compile.py` that would not delete and redownload the repositories.

**Comment by neurolabusc** [comment]
See my comments for [here](https://github.com/neurolabusc/pigz-bench/issues/4). 

1. Run script `a_compile.py` **once** only to download and install reference variations of `pigz` and the testing `corpus`.
```
a_compile.py
``` 
2. Download the custom zlib you want to test and modify **once**, e.g.
```
git clone --branch fixes/gh-536-wsize https://github.com/nmoinvaz/zlib-ng.git
```
3. Compile a new version of the zlib locally and rebuild pigz for this custom library, copying the new copy of pigz to the `exe` folder. Assuming the previous step created the folder `zlib-ng` and you want the new version of pigz to be called `pigzng` the Unix commands are
```
#!/bin/bash
cd zlib-ng
make clean
./configure --static --zlib-compat
make
cd ../pigz/build
rm -rf *
cmake -DZLIB_IMPLEMENTATION=Custom -DZLIB_ROOT=../../zlib-ng ..
make
cp ./bin/pigz ../../exe/pigzng
```
4. Run the scripts `b_speed_threads.py`, `c_decompress.py`, `d_speed_size.py`  as desired to test the performance of your local zlib. If you are unhappy, you can edit the files of your zlib and repeat steps 3 and 4.
