### ISSUE TITLE
Enumerate SuperBuild directory

### ISSUE THREAD

**Issue by nmoinvaz** [neurolabusc/pigz-bench-python#2]
Instead of specifying the builds in ./a_compile.py. It might be better to just enumerate the SuperBuild for those. That way if I want to add my own repsotory, I can just drop in an External-Nathan.cmake into the SuperBuild directory and it would pick it up

**Comment by neurolabusc** [comment]
See my comments for [issue 1](https://github.com/neurolabusc/pigz-bench-python/issues/1). The intention for `a_compile.py` is that it is run once to compile the reference variations of pigz. You can easily compile and install a custom version of pigz based on your private version of zlib using a few lines of code in the terminal. The subsequent scripts can subsequently compare your variation to the reference variations.

**Comment by nmoinvaz** [comment]
Ok thanks.
