### ISSUE TITLE
Graph compression ratio

### ISSUE THREAD

**Issue by nmoinvaz** [neurolabusc/pigz-bench-python#3]
The compression speed graph is great. It would also be good to possibly have another graph that comes up after it, that shows difference in compression ratio. This is to ensure that nothing has been regressed and possibly see if the improvements increase/decrease compression. Thanks for the excellent test harness!

**Comment by neurolabusc** [comment]
Try the `d_speed_size.py` or the newer `f_speed_size_decompress.py` script. These test each tool with its default number of threads, and plots the compression speed versus compression ratio, so you can see tradeoffs. The newer script allows you to easily add new alternatives, for example `xz`, `lbzip2` and `lz4`.
